# Generated by Django 5.0 on 2023-12-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('clicks', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('img_url', models.ImageField(blank=True, upload_to='images/')),
                ('link', models.URLField()),
                ('unique_id_ad', models.AutoField(primary_key=True, serialize=False)),
                ('clicks_ad', models.IntegerField(default=0)),
                ('views_ad', models.IntegerField(default=0)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='mangement_advertiser.advertiser')),
            ],
        ),
    ]
