# Generated by Django 5.0 on 2023-12-29 16:03

import django.db.models.deletion
import mangement_advertiser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=(mangement_advertiser.models.BaseAdvertising, models.Model),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.URLField()),
                ('link', models.URLField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement_advertiser.advertiser')),
            ],
            bases=(mangement_advertiser.models.BaseAdvertising, models.Model),
        ),
    ]
