# Generated by Django 5.0 on 2023-12-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='unique_id_ad',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='unique_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
